name: ai_subspace_env
channels:
  - conda-forge
  - defaults
  - bioconda
  - nvidia
dependencies:
  - python=3.10
  - pip
  - wheel
  - scipy
  - pip:
      - annotated-types==0.7.0
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - click==8.1.8
      - colorama==0.4.6
      - contourpy==1.3.1
      - cycler==0.12.1
      - docker-pycreds==0.4.0
      - filelock==3.13.1
      - fonttools==4.56.0
      - fsspec==2024.6.1
      - gitdb==4.0.12
      - gitpython==3.1.44
      - h5py==3.13.0
      - idna==3.10
      - jinja2==3.1.4
      - joblib==1.4.2
      - kiwisolver==1.4.8
      - markupsafe==2.1.5
      - matplotlib==3.10.1
      - mpmath==1.3.0
      - networkx==3.3
      - numpy==2.1.2
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - packaging==24.2
      - pillow==11.0.0
      - platformdirs==4.3.7
      - protobuf==5.29.4
      - psutil==7.0.0
      - pydantic==2.11.1
      - pydantic-core==2.33.0
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.2
      - requests==2.32.3
      - scikit-learn==1.6.1
      - sentry-sdk==2.24.1
      - setproctitle==1.3.5
      - setuptools==70.2.0
      - six==1.17.0
      - smmap==5.0.2
      - threadpoolctl==3.6.0
      - torch==2.7.0+cu126
      - torchaudio==2.7.0+cu126
      - torchvision==0.22.0+cu126
      - tqdm==4.67.1
      - triton==3.3.0
      - typing-extensions==4.12.2
      - typing-inspection==0.4.0
      - urllib3==2.3.0
      - wandb==0.19.8
